addr = "localhost:8080"
extaddr = "https://localhost:8080"
#certificate = ""
#certificatekey = ""
#rootca = ["/tmp/ca.cert.pem"]
#webstatic = "/tmp"

[logging]
namespace="graphql-ui-template"
stashHost=""
stashPortNb=0
traceLevel="DEBUG"
stashTraceLevel="ERROR"
filename=""

[keycloak]
realm="test"
addr="https://auth.ub.unibas.ch/"
callback="https://localhost:8080"
clientId="graphql-demo"
